# app/config/schema.py
# -*- coding: utf-8 -*-
"""
所有設定的 Schema 定義。
每個設定項包含：label、category、type、default、reload_required 等欄位。
category 對應 GUI 設定頁的分頁。
reload_required=False 表示即時生效（hot reload），True 表示需重啟訓練。
"""

CONFIG_SCHEMA: dict[str, dict] = {

    # ── GUI 介面（即時生效）────────────────────────────────────────────
    "gui.enabled": {
        "label": "啟用 GUI",
        "category": "gui",
        "type": "bool",
        "default": True,
        "reload_required": True,
        "description": "啟用視覺化訓練介面（需重啟生效）",
    },
    "gui.board_fps": {
        "label": "盤面 FPS",
        "category": "gui",
        "type": "int",
        "default": 20,
        "min": 1,
        "max": 60,
        "reload_required": False,
        "description": "盤面即時更新最高 FPS，降低可減少 CPU 占用",
    },
    "gui.max_boards": {
        "label": "最多盤面數",
        "category": "gui",
        "type": "int",
        "default": 4,
        "min": 1,
        "max": 9,
        "reload_required": True,
        "description": "同時顯示的盤面數量（1→1x1, 4→2x2, 9→3x3），需重啟生效",
    },

    # ── AI 訓練（需重啟）───────────────────────────────────────────────
    "training.lr": {
        "label": "學習率",
        "category": "training",
        "type": "float",
        "default": 3e-4,
        "min": 1e-6,
        "max": 1e-1,
        "reload_required": True,
        "description": "PPO 優化器學習率",
    },
    "training.gamma": {
        "label": "折扣係數 (γ)",
        "category": "training",
        "type": "float",
        "default": 0.99,
        "min": 0.8,
        "max": 1.0,
        "reload_required": True,
        "description": "未來獎勵的折扣比例",
    },
    "training.gae_lambda": {
        "label": "GAE λ",
        "category": "training",
        "type": "float",
        "default": 0.95,
        "min": 0.5,
        "max": 1.0,
        "reload_required": True,
        "description": "Generalized Advantage Estimation 的 lambda 值",
    },
    "training.ppo_clip": {
        "label": "PPO Clip ε",
        "category": "training",
        "type": "float",
        "default": 0.2,
        "min": 0.05,
        "max": 0.5,
        "reload_required": True,
        "description": "PPO 策略比例裁剪範圍",
    },
    "training.ppo_epochs": {
        "label": "PPO 更新輪數",
        "category": "training",
        "type": "int",
        "default": 10,
        "min": 1,
        "max": 50,
        "reload_required": True,
        "description": "每次 rollout 後的 PPO 更新迭代次數",
    },
    "training.ppo_minibatch": {
        "label": "Mini-batch 大小",
        "category": "training",
        "type": "int",
        "default": 64,
        "min": 8,
        "max": 512,
        "reload_required": True,
        "description": "PPO 更新時的 mini-batch 大小",
    },
    "training.rollout_steps": {
        "label": "Rollout 步數",
        "category": "training",
        "type": "int",
        "default": 512,
        "min": 64,
        "max": 4096,
        "reload_required": True,
        "description": "每次收集的經驗步數，達到後觸發 PPO 更新",
    },
    "training.mrv_mix_prob": {
        "label": "MRV 初始混合率",
        "category": "training",
        "type": "float",
        "default": 0.9,
        "min": 0.0,
        "max": 1.0,
        "reload_required": True,
        "description": "訓練初期使用 MRV 專家示範的機率（Phase 1 起點）",
    },
    "training.mrv_decay_steps": {
        "label": "MRV 衰減步數（Phase 2 結束點）",
        "category": "training",
        "type": "int",
        "default": 90000,
        "min": 1000,
        "max": 500000,
        "reload_required": True,
        "description": "Phase 2 完成時（MRV 從 0.40 降至 0.10）所需的總步數",
    },
    "training.save_every_episodes": {
        "label": "自動儲存間隔（回合）",
        "category": "training",
        "type": "int",
        "default": 100,
        "min": 10,
        "max": 10000,
        "reload_required": False,
        "description": "每隔多少回合自動儲存模型",
    },
    "training.device": {
        "label": "運算裝置",
        "category": "training",
        "type": "str",
        "default": "cuda",
        "options": ["cuda", "cpu"],
        "reload_required": True,
        "description": "訓練使用的運算裝置（cuda 需要 NVIDIA GPU）",
    },
    "training.use_fp16": {
        "label": "混合精度訓練 (FP16)",
        "category": "training",
        "type": "bool",
        "default": True,
        "reload_required": True,
        "description": "啟用 FP16 混合精度以加速訓練、降低顯存占用",
    },
    "training.level_dist": {
        "label": "難度分布",
        "category": "training",
        "type": "str",
        "default": '{"1": 0.6, "2": 0.3, "3": 0.1}',
        "reload_required": False,
        "description": "爬蟲抓題難度比例，JSON 格式，key=難度(1-4)，value=比例",
    },

    # ── 爬蟲（需重啟執行緒）────────────────────────────────────────────
    "crawler.producer_workers": {
        "label": "爬蟲執行緒數",
        "category": "crawler",
        "type": "int",
        "default": 20,
        "min": 1,
        "max": 100,
        "reload_required": True,
        "description": "背景爬蟲並行執行緒數量",
    },
    "crawler.min_delay": {
        "label": "最小延遲（秒）",
        "category": "crawler",
        "type": "float",
        "default": 0.0,
        "min": 0.0,
        "max": 10.0,
        "reload_required": False,
        "description": "每次成功抓題後的最小等待秒數",
    },
    "crawler.max_delay": {
        "label": "最大延遲（秒）",
        "category": "crawler",
        "type": "float",
        "default": 0.3,
        "min": 0.0,
        "max": 30.0,
        "reload_required": False,
        "description": "每次成功抓題後的最大等待秒數",
    },
    "crawler.page_timeout_ms": {
        "label": "頁面逾時（毫秒）",
        "category": "crawler",
        "type": "int",
        "default": 8000,
        "min": 1000,
        "max": 60000,
        "reload_required": False,
        "description": "HTTP 請求逾時時間（毫秒）",
    },
    "crawler.max_pool_size": {
        "label": "題庫上限",
        "category": "crawler",
        "type": "int",
        "default": 50000,
        "min": 100,
        "max": 1000000,
        "reload_required": False,
        "description": "題庫最多儲存的題目數量，達到後停止爬蟲",
    },
    "crawler.min_pool_size": {
        "label": "題庫下限",
        "category": "crawler",
        "type": "int",
        "default": 30,
        "min": 1,
        "max": 10000,
        "reload_required": False,
        "description": "題庫低於此數量時恢復爬蟲",
    },

    # ── Proxy（需重啟）─────────────────────────────────────────────────
    "proxy.enabled": {
        "label": "啟用 Proxy",
        "category": "proxy",
        "type": "bool",
        "default": True,
        "reload_required": True,
        "description": "停用則直連 websudoku.com（容易被封鎖）",
    },
    "proxy.validate": {
        "label": "啟動時驗證 Proxy",
        "category": "proxy",
        "type": "bool",
        "default": True,
        "reload_required": True,
        "description": "啟動時過濾無效 Proxy（建議開啟）",
    },
    "proxy.validate_workers": {
        "label": "驗證並行數",
        "category": "proxy",
        "type": "int",
        "default": 100,
        "min": 1,
        "max": 500,
        "reload_required": True,
        "description": "Proxy 驗證時的並行執行緒數",
    },
    "proxy.validate_timeout": {
        "label": "驗證逾時（秒）",
        "category": "proxy",
        "type": "int",
        "default": 3,
        "min": 1,
        "max": 30,
        "reload_required": True,
        "description": "每個 Proxy 驗證的逾時秒數",
    },

    # ── 日誌（即時生效）────────────────────────────────────────────────
    "logging.print_episode_result": {
        "label": "顯示回合結果",
        "category": "logging",
        "type": "bool",
        "default": True,
        "reload_required": False,
        "description": "每回合結束後是否在終端顯示結果",
    },
    "logging.print_every_episodes": {
        "label": "統計顯示間隔",
        "category": "logging",
        "type": "int",
        "default": 10,
        "min": 1,
        "max": 1000,
        "reload_required": False,
        "description": "每隔多少回合顯示一次滾動統計",
    },
    "logging.print_rolling_stats": {
        "label": "顯示滾動統計",
        "category": "logging",
        "type": "bool",
        "default": True,
        "reload_required": False,
        "description": "是否顯示最近 N 回合的平均統計",
    },
    "logging.print_agent_update_log": {
        "label": "顯示 Agent 更新日誌",
        "category": "logging",
        "type": "bool",
        "default": True,
        "reload_required": False,
        "description": "PPO 更新後是否顯示 loss 等資訊",
    },
    "logging.print_producer_success": {
        "label": "顯示爬蟲成功日誌",
        "category": "logging",
        "type": "bool",
        "default": False,
        "reload_required": False,
        "description": "每插入一道新題是否印出一行（20 個 worker 時較吵）",
    },

    # ── 執行模式（需重啟）──────────────────────────────────────────────
    "run.mode": {
        "label": "執行模式",
        "category": "run",
        "type": "str",
        "default": "train",
        "options": ["train", "eval"],
        "reload_required": True,
        "description": "train=訓練模式，eval=純評估（不更新模型）",
    },
    "run.infinite_training": {
        "label": "無限訓練",
        "category": "run",
        "type": "bool",
        "default": True,
        "reload_required": True,
        "description": "開啟後忽略回合數限制，持續訓練直到手動停止",
    },
    "run.train_episodes": {
        "label": "訓練回合數上限",
        "category": "run",
        "type": "int",
        "default": 300,
        "min": 1,
        "max": 10000000,
        "reload_required": True,
        "description": "無限訓練關閉時，訓練到此回合數後停止",
    },
    "run.eval_episodes": {
        "label": "評估回合數",
        "category": "run",
        "type": "int",
        "default": 30,
        "min": 1,
        "max": 100000,
        "reload_required": True,
        "description": "eval 模式下的回合總數",
    },
    "run.max_steps_per_episode": {
        "label": "每回合最大步數",
        "category": "run",
        "type": "int",
        "default": 100,
        "min": 1,
        "max": 10000,
        "reload_required": True,
        "description": "超過此步數強制結束該回合",
    },

    # ── 資料庫（需重啟）────────────────────────────────────────────────
    "db.path": {
        "label": "DB 路徑",
        "category": "db",
        "type": "str",
        "default": "data/puzzle_pool.db",
        "reload_required": True,
        "description": "SQLite 題庫路徑（相對於 main_train.py）",
    },
    "db.worker_name": {
        "label": "訓練 Worker 名稱",
        "category": "db",
        "type": "str",
        "default": "trainer_main",
        "reload_required": True,
        "description": "DB 鎖記錄中使用的 Worker 識別名稱",
    },

    # ── 爬蟲補充 ───────────────────────────────────────────────────────
    "crawler.max_tries_per_puzzle": {
        "label": "每題最大嘗試次數",
        "category": "crawler",
        "type": "int",
        "default": 2147483647,
        "min": 1,
        "max": 2147483647,
        "reload_required": False,
        "description": "同一道題嘗試超過此次數後標記為 skipped（2147483647=無限）",
    },
    "crawler.min_expected_givens": {
        "label": "最少初始格子數",
        "category": "crawler",
        "type": "int",
        "default": 10,
        "min": 1,
        "max": 80,
        "reload_required": False,
        "description": "抓到的題目初始格子數低於此值時視為無效",
    },
    "crawler.max_expected_givens": {
        "label": "最多初始格子數",
        "category": "crawler",
        "type": "int",
        "default": 60,
        "min": 1,
        "max": 81,
        "reload_required": False,
        "description": "抓到的題目初始格子數高於此值時視為無效",
    },

    # ── Proxy 補充 ─────────────────────────────────────────────────────
    "proxy.validate_count": {
        "label": "驗證代理數量限制",
        "category": "proxy",
        "type": "int",
        "default": -1,
        "min": -1,
        "max": 100000,
        "reload_required": True,
        "description": "-1 = 驗證所有已下載的代理",
    },

    # ── 日誌補充 ────────────────────────────────────────────────────────
    "logging.print_run_config": {
        "label": "啟動時顯示設定摘要",
        "category": "logging",
        "type": "bool",
        "default": True,
        "reload_required": False,
        "description": "訓練開始時印出設定摘要到終端",
    },
    "logging.print_web_retry": {
        "label": "顯示 Web 重試日誌",
        "category": "logging",
        "type": "bool",
        "default": True,
        "reload_required": False,
        "description": "顯示爬蟲 HTTP 失敗與重試訊息",
    },
    "logging.print_pool": {
        "label": "顯示題庫操作日誌",
        "category": "logging",
        "type": "bool",
        "default": True,
        "reload_required": False,
        "description": "顯示爬蟲執行緒啟停、題庫等待等訊息",
    },
    "logging.producer_debug": {
        "label": "爬蟲 Debug 模式",
        "category": "logging",
        "type": "bool",
        "default": False,
        "reload_required": False,
        "description": "顯示 HTTP 狀態碼、HTML 內容等詳細爬蟲訊息",
    },
    "logging.rolling_stats_window": {
        "label": "滾動統計視窗大小",
        "category": "logging",
        "type": "int",
        "default": 100,
        "min": 1,
        "max": 10000,
        "reload_required": False,
        "description": "計算成功率與平均獎勵時使用最近 N 回合",
    },

    # ── 訓練補充（需重啟）──────────────────────────────────────────────
    "training.agent_type": {
        "label": "Agent 類型",
        "category": "training",
        "type": "str",
        "default": "torch",
        "options": ["torch", "mrv"],
        "reload_required": True,
        "description": "torch=PPO 神經網路，mrv=純 MRV 啟發式",
    },
    "training.train_policy_mode": {
        "label": "訓練策略取樣方式",
        "category": "training",
        "type": "str",
        "default": "sample",
        "options": ["sample", "greedy"],
        "reload_required": True,
        "description": "訓練時動作取樣方式",
    },
    "training.eval_policy_mode": {
        "label": "評估策略取樣方式",
        "category": "training",
        "type": "str",
        "default": "greedy",
        "options": ["sample", "greedy"],
        "reload_required": True,
        "description": "eval 模式時動作取樣方式",
    },
    "training.value_coef": {
        "label": "值函數損失係數",
        "category": "training",
        "type": "float",
        "default": 0.5,
        "min": 0.0,
        "max": 1.0,
        "reload_required": True,
        "description": "PPO 損失中值函數部分的權重",
    },
    "training.grad_clip": {
        "label": "梯度裁剪",
        "category": "training",
        "type": "float",
        "default": 0.5,
        "min": 0.0,
        "max": 10.0,
        "reload_required": True,
        "description": "梯度 L2 norm 裁剪閾值（0=不裁剪）",
    },
    "training.adaptive_entropy": {
        "label": "自適應熵係數",
        "category": "training",
        "type": "bool",
        "default": True,
        "reload_required": True,
        "description": "自動調整熵係數以維持目標熵值",
    },
    "training.target_entropy": {
        "label": "目標熵值",
        "category": "training",
        "type": "float",
        "default": 0.5,
        "min": 0.0,
        "max": 5.0,
        "reload_required": True,
        "description": "自適應熵調整的目標熵值",
    },
    "training.entropy_init": {
        "label": "初始熵係數",
        "category": "training",
        "type": "float",
        "default": 0.05,
        "min": 0.0,
        "max": 1.0,
        "reload_required": True,
        "description": "訓練開始時的熵係數初始值",
    },
    "training.entropy_lr": {
        "label": "熵係數學習率",
        "category": "training",
        "type": "float",
        "default": 3e-4,
        "min": 1e-6,
        "max": 1.0,
        "reload_required": True,
        "description": "調整熵係數時的梯度步長",
    },
    "training.min_entropy_coef": {
        "label": "最小熵係數",
        "category": "training",
        "type": "float",
        "default": 0.001,
        "min": 0.0,
        "max": 1.0,
        "reload_required": True,
        "description": "熵係數自適應調整的下界",
    },
    "training.max_entropy_coef": {
        "label": "最大熵係數",
        "category": "training",
        "type": "float",
        "default": 1.0,
        "min": 0.0,
        "max": 10.0,
        "reload_required": True,
        "description": "熵係數自適應調整的上界",
    },
    "training.cell_dim": {
        "label": "Cell 嵌入維度",
        "category": "training",
        "type": "int",
        "default": 128,
        "min": 16,
        "max": 512,
        "reload_required": True,
        "description": "神經網路每個格子嵌入的維度",
    },
    "training.head_dim": {
        "label": "Constraint Head 維度",
        "category": "training",
        "type": "int",
        "default": 64,
        "min": 8,
        "max": 256,
        "reload_required": True,
        "description": "行/列/宮約束 Head 的隱藏維度",
    },
    "training.normalize_returns": {
        "label": "正規化 Returns",
        "category": "training",
        "type": "bool",
        "default": True,
        "reload_required": True,
        "description": "PPO 更新前對 Returns 進行 running mean/std 正規化",
    },
    "training.mrv_min_prob": {
        "label": "MRV Floor（Phase 3 固定值）",
        "category": "training",
        "type": "float",
        "default": 0.05,
        "min": 0.0,
        "max": 0.5,
        "reload_required": True,
        "description": "Phase 3 的固定 MRV 機率；設 0 表示完全關閉 teacher",
    },
    "training.phase1_steps": {
        "label": "Phase 1 步數上限",
        "category": "training",
        "type": "int",
        "default": 30000,
        "min": 1000,
        "max": 500000,
        "reload_required": True,
        "description": "Phase 1→2 的 time backstop；success_rate≥tau1 可提早觸發",
    },
    "training.phase2_steps": {
        "label": "Phase 2 步數上限",
        "category": "training",
        "type": "int",
        "default": 90000,
        "min": 1000,
        "max": 1000000,
        "reload_required": True,
        "description": "Phase 2→3 的 time backstop；success_rate≥tau2 可提早觸發",
    },
    "training.phase1_tau": {
        "label": "Phase 1 success 門檻",
        "category": "training",
        "type": "float",
        "default": 0.30,
        "min": 0.0,
        "max": 1.0,
        "reload_required": True,
        "description": "最近 100 回合成功率達此值時提前進入 Phase 2",
    },
    "training.phase2_tau": {
        "label": "Phase 2 success 門檻",
        "category": "training",
        "type": "float",
        "default": 0.65,
        "min": 0.0,
        "max": 1.0,
        "reload_required": True,
        "description": "最近 100 回合成功率達此值時提前進入 Phase 3",
    },
    "training.teacher_max_cand": {
        "label": "Teacher 最大 candidate 數",
        "category": "training",
        "type": "int",
        "default": 4,
        "min": 1,
        "max": 9,
        "reload_required": True,
        "description": "格子 candidate 數超過此值時 teacher 放棄出手（Level 5），不產生 BC loss",
    },
    "training.policy_demo_capacity": {
        "label": "PolicyDemoStore 容量（步數）",
        "category": "training",
        "type": "int",
        "default": 2048,
        "min": 128,
        "max": 32768,
        "reload_required": True,
        "description": "Phase 3 自我改善回路的 ring buffer 大小",
    },
    "training.policy_demo_weight": {
        "label": "Policy Demo Soft BC 權重",
        "category": "training",
        "type": "float",
        "default": 0.30,
        "min": 0.0,
        "max": 2.0,
        "reload_required": True,
        "description": "Phase 3 中 policy demo soft BC loss 的係數",
    },
    "training.success_bonus": {
        "label": "成功額外獎勵",
        "category": "training",
        "type": "float",
        "default": 100.0,
        "min": 0.0,
        "max": 1000.0,
        "reload_required": True,
        "description": "成功解題時疊加的額外獎勵",
    },
    "training.dead_end_penalty": {
        "label": "死局額外懲罰",
        "category": "training",
        "type": "float",
        "default": 0.0,
        "min": -100.0,
        "max": 0.0,
        "reload_required": True,
        "description": "無合法動作時疊加的額外懲罰（通常設 0）",
    },
    "training.bc_coef": {
        "label": "BC Loss 係數",
        "category": "training",
        "type": "float",
        "default": 1.0,
        "min": 0.0,
        "max": 5.0,
        "reload_required": True,
        "description": "Behavior Cloning 損失權重（MRV 專家示範的模仿強度）",
    },

    # ── 模型儲存（需重啟）──────────────────────────────────────────────
    "model.dir": {
        "label": "模型目錄",
        "category": "model",
        "type": "str",
        "default": "models",
        "reload_required": True,
        "description": "儲存模型 .pt 檔案的目錄",
    },
    "model.path": {
        "label": "模型路徑",
        "category": "model",
        "type": "str",
        "default": "models/sudoku_policy_latest.pt",
        "reload_required": True,
        "description": "模型 checkpoint 的完整路徑",
    },
    "model.auto_load": {
        "label": "啟動時自動載入模型",
        "category": "model",
        "type": "bool",
        "default": True,
        "reload_required": True,
        "description": "有現有模型時自動繼續訓練",
    },
    "model.reset_optimizer_on_load": {
        "label": "載入時重設優化器",
        "category": "model",
        "type": "bool",
        "default": False,
        "reload_required": True,
        "description": "載入 checkpoint 時是否重設優化器狀態",
    },
    "model.reset_counters_on_load": {
        "label": "載入時重設計數器",
        "category": "model",
        "type": "bool",
        "default": False,
        "reload_required": True,
        "description": "載入 checkpoint 時是否重設回合/更新計數",
    },
}

CATEGORY_LABELS: dict[str, str] = {
    "gui":      "介面",
    "training": "AI 訓練",
    "crawler":  "爬蟲",
    "proxy":    "Proxy",
    "logging":  "日誌",
    "run":      "執行模式",
    "db":       "資料庫",
    "model":    "模型",
}
