// Per-chapter palette + ambient shapes config — mirror of outline-visual.md §6
export const chapters = [
  {
    id: 1,
    name: 'coldopen',
    mood: '探索/好奇/白日夢',
    primary: 'cream+紫',
    secondary: '黃',
    climaxAmbient: '紅',
    tint: 'rgba(196,181,253,0.08)',
    density: 'mid',
    ambientShapes: [
      { position: 'tl', shape: 'star',     color: 'secondary', rotation: 15 },
      { position: 'tr', shape: 'square',   color: 'muted',     rotation: -8 },
      { position: 'bl', shape: 'circle',   color: 'accent',    rotation: 0 },
      { position: 'br', shape: 'outline-question', color: 'ink', rotation: 12 },
      { position: 'mr', shape: 'circle',   color: 'secondary', rotation: -3 },
    ],
  },
  {
    id: 2,
    name: 'ml-map',
    mood: '教學/理性',
    primary: 'cream+黑',
    secondary: '灰線',
    climaxAmbient: '紅',
    tint: 'rgba(0,0,0,0.04)',
    density: 'low',
    ambientShapes: [
      { position: 'tl', shape: 'star',   color: 'ink',     rotation: -10, outline: true },
      { position: 'tr', shape: 'square', color: '#888',    rotation: 5 },
      { position: 'bl', shape: 'pill',   color: 'ink',     rotation: 0 },
      { position: 'br', shape: 'circle', color: 'accent',  rotation: -8 },
    ],
  },
  {
    id: 3,
    name: 'llm-vs-rl',
    mood: '對比/分歧',
    primary: 'cream',
    secondary: '紫+黃',
    climaxAmbient: '紅',
    tint: 'rgba(196,181,253,0.06)',
    density: 'mid',
    ambientShapes: [
      { position: 'tl', shape: 'square',   color: 'muted',     rotation: -5 },
      { position: 'tr', shape: 'circle',   color: 'secondary', rotation: 10 },
      { position: 'bl', shape: 'triangle', color: 'muted',     rotation: 3 },
      { position: 'br', shape: 'square',   color: 'secondary', rotation: 38 },
      { position: 'mr', shape: 'outline-question', color: 'accent', rotation: 8 },
    ],
  },
  {
    id: 4,
    name: 'data-hunt',
    mood: '戰鬥/受害',
    primary: 'cream+黑mono',
    secondary: '黃',
    climaxAmbient: '紅',
    tint: 'rgba(255,217,61,0.06)',
    density: 'mid',
    ambientShapes: [
      { position: 'tl', shape: 'square', color: 'ink',       rotation: 5 },
      { position: 'tr', shape: 'star',   color: 'secondary', rotation: -10 },
      { position: 'bl', shape: 'circle', color: 'accent',    rotation: 12 },
      { position: 'br', shape: 'pill',   color: 'ink',       rotation: -3, outline: true },
    ],
  },
  {
    id: 5,
    name: 'legacy',
    mood: '崩盤#1',
    primary: 'cream+紅邊',
    secondary: '紅叉叉',
    climaxAmbient: '紅 flash',
    tint: 'rgba(255,107,107,0.07)',
    density: 'mid',
    ambientShapes: [
      { position: 'tl', shape: 'square', color: 'accent', rotation: 60 },
      { position: 'tr', shape: 'circle', color: 'accent', rotation: -5 },
      { position: 'bl', shape: 'square', color: 'accent', rotation: 8, outline: true },
      { position: 'br', shape: 'pill',   color: 'accent', rotation: -3 },
    ],
  },
  {
    id: 6,
    name: 'sb3',
    mood: '戀愛錯覺→崩盤#2',
    primary: '粉紅',
    secondary: '紅',
    climaxAmbient: '灰→紅stamp',
    tint: 'rgba(255,182,193,0.10)',
    density: 'mid',
    ambientShapes: [
      { position: 'tl', shape: 'circle', color: '#FFB6C1', rotation: 10 },
      { position: 'tr', shape: 'circle', color: 'accent',  rotation: -6 },
      { position: 'bl', shape: 'square', color: '#FFB6C1', rotation: 3 },
      { position: 'br', shape: 'pill',   color: 'accent',  rotation: -10 },
      { position: 'ml', shape: 'circle', color: '#999',    rotation: 5 },
    ],
  },
  {
    id: 7,
    name: 'reasoner',
    mood: '嚴肅/死結',
    primary: 'cream+黑',
    secondary: '多色',
    climaxAmbient: '紅底+黃0',
    tint: 'rgba(0,0,0,0.05)',
    density: 'high',
    ambientShapes: [
      { position: 'tl', shape: 'square',   color: 'accent',    rotation: -8 },
      { position: 'tr', shape: 'star',     color: 'muted',     rotation: 12 },
      { position: 'bl', shape: 'square',   color: 'secondary', rotation: 50 },
      { position: 'br', shape: 'outline-question', color: 'ink', rotation: -10 },
      { position: 'mr', shape: 'circle',   color: 'muted',     rotation: 3 },
      { position: 'ml', shape: 'triangle', color: 'accent',    rotation: -5 },
    ],
  },
  {
    id: 8,
    name: 'apprentice',
    mood: '突破/光明',
    primary: 'cream+金黃',
    secondary: '紫',
    climaxAmbient: '黃 +50',
    tint: 'rgba(255,217,61,0.10)',
    density: 'mid',
    ambientShapes: [
      { position: 'tl', shape: 'star',   color: 'secondary', rotation: 10 },
      { position: 'tr', shape: 'square', color: 'muted',     rotation: -8 },
      { position: 'bl', shape: 'circle', color: 'secondary', rotation: 3 },
      { position: 'br', shape: 'star',   color: 'secondary', rotation: -12 },
    ],
  },
  {
    id: 9,
    name: 'callback',
    mood: '收斂/哲思/收尾',
    primary: 'cream',
    secondary: '紫',
    climaxAmbient: '紅 (電費小偷)',
    tint: 'rgba(196,181,253,0.07)',
    density: 'high',
    ambientShapes: [
      { position: 'tl', shape: 'circle', color: 'muted',     rotation: 5 },
      { position: 'tr', shape: 'star',   color: 'accent',    rotation: -10 },
      { position: 'bl', shape: 'square', color: 'muted',     rotation: 8, outline: true },
      { position: 'br', shape: 'outline-question', color: '#888', rotation: -3 },
    ],
  },
];

export function getChapter(id) {
  return chapters.find(c => c.id === id) ?? chapters[0];
}
